// Monopoly board: 40 spaces, clockwise from GO
// Types: 'go', 'property', 'chance', 'communityChest', 'tax', 'jail', 'freeParking', 'goToJail', 'railroad', 'utility'

const BOARD_SPACES = [
  {
    id: 0,
    name: 'GO',
    type: 'go',
    description: 'Collect $200 as you pass',
  },
  {
    id: 1,
    name: 'Mediterranean Avenue',
    shortName: 'Mediterr.',
    type: 'property',
    group: 'brown',
    price: 60,
    rent: [2, 10, 30, 90, 160, 250],
    housePrice: 50,
  },
  {
    id: 2,
    name: 'Community Chest',
    shortName: 'Com.Chest',
    type: 'communityChest',
    description: 'Draw a Community Chest card',
  },
  {
    id: 3,
    name: 'Baltic Avenue',
    shortName: 'Baltic',
    type: 'property',
    group: 'brown',
    price: 60,
    rent: [4, 20, 60, 180, 320, 450],
    housePrice: 50,
  },
  {
    id: 4,
    name: 'Income Tax',
    shortName: 'Inc. Tax',
    type: 'tax',
    description: 'Pay $200',
    amount: 200,
  },
  {
    id: 5,
    name: 'Reading Railroad',
    shortName: 'Reading',
    type: 'railroad',
    price: 200,
    rent: [25, 50, 100, 200],
  },
  {
    id: 6,
    name: 'Oriental Avenue',
    shortName: 'Oriental',
    type: 'property',
    group: 'lightBlue',
    price: 100,
    rent: [6, 30, 90, 270, 400, 550],
    housePrice: 50,
  },
  {
    id: 7,
    name: 'Chance',
    type: 'chance',
    description: 'Draw a Chance card',
  },
  {
    id: 8,
    name: 'Vermont Avenue',
    shortName: 'Vermont',
    type: 'property',
    group: 'lightBlue',
    price: 100,
    rent: [6, 30, 90, 270, 400, 550],
    housePrice: 50,
  },
  {
    id: 9,
    name: 'Connecticut Avenue',
    shortName: 'Connect.',
    type: 'property',
    group: 'lightBlue',
    price: 120,
    rent: [8, 40, 100, 300, 450, 600],
    housePrice: 50,
  },
  {
    id: 10,
    name: 'Jail / Just Visiting',
    type: 'jail',
    description: 'Just visiting - no effect',
  },
  {
    id: 11,
    name: 'St. Charles Place',
    shortName: 'St.Charls',
    type: 'property',
    group: 'pink',
    price: 140,
    rent: [10, 50, 150, 450, 625, 750],
    housePrice: 100,
  },
  {
    id: 12,
    name: 'Electric Company',
    shortName: 'Electric',
    type: 'utility',
    price: 150,
  },
  {
    id: 13,
    name: 'States Avenue',
    shortName: 'States',
    type: 'property',
    group: 'pink',
    price: 140,
    rent: [10, 50, 150, 450, 625, 750],
    housePrice: 100,
  },
  {
    id: 14,
    name: 'Virginia Avenue',
    shortName: 'Virginia',
    type: 'property',
    group: 'pink',
    price: 160,
    rent: [12, 60, 180, 500, 700, 900],
    housePrice: 100,
  },
  {
    id: 15,
    name: 'Pennsylvania Railroad',
    shortName: 'Penn. RR',
    type: 'railroad',
    price: 200,
    rent: [25, 50, 100, 200],
  },
  {
    id: 16,
    name: 'St. James Place',
    shortName: 'St. James',
    type: 'property',
    group: 'orange',
    price: 180,
    rent: [14, 70, 200, 550, 750, 950],
    housePrice: 100,
  },
  {
    id: 17,
    name: 'Community Chest',
    shortName: 'Com.Chest',
    type: 'communityChest',
    description: 'Draw a Community Chest card',
  },
  {
    id: 18,
    name: 'Tennessee Avenue',
    shortName: 'Tennessee',
    type: 'property',
    group: 'orange',
    price: 180,
    rent: [14, 70, 200, 550, 750, 950],
    housePrice: 100,
  },
  {
    id: 19,
    name: 'New York Avenue',
    shortName: 'New York',
    type: 'property',
    group: 'orange',
    price: 200,
    rent: [16, 80, 220, 600, 800, 1000],
    housePrice: 100,
  },
  {
    id: 20,
    name: 'Free Parking',
    type: 'freeParking',
    description: 'No effect - rest here',
  },
  {
    id: 21,
    name: 'Kentucky Avenue',
    shortName: 'Kentucky',
    type: 'property',
    group: 'red',
    price: 220,
    rent: [18, 90, 250, 700, 875, 1050],
    housePrice: 150,
  },
  {
    id: 22,
    name: 'Chance',
    type: 'chance',
    description: 'Draw a Chance card',
  },
  {
    id: 23,
    name: 'Indiana Avenue',
    shortName: 'Indiana',
    type: 'property',
    group: 'red',
    price: 220,
    rent: [18, 90, 250, 700, 875, 1050],
    housePrice: 150,
  },
  {
    id: 24,
    name: 'Illinois Avenue',
    shortName: 'Illinois',
    type: 'property',
    group: 'red',
    price: 240,
    rent: [20, 100, 300, 750, 925, 1100],
    housePrice: 150,
  },
  {
    id: 25,
    name: 'B&O Railroad',
    shortName: 'B&O RR',
    type: 'railroad',
    price: 200,
    rent: [25, 50, 100, 200],
  },
  {
    id: 26,
    name: 'Atlantic Avenue',
    shortName: 'Atlantic',
    type: 'property',
    group: 'yellow',
    price: 260,
    rent: [22, 110, 330, 800, 975, 1150],
    housePrice: 150,
  },
  {
    id: 27,
    name: 'Ventnor Avenue',
    shortName: 'Ventnor',
    type: 'property',
    group: 'yellow',
    price: 260,
    rent: [22, 110, 330, 800, 975, 1150],
    housePrice: 150,
  },
  {
    id: 28,
    name: 'Water Works',
    shortName: 'WaterWrks',
    type: 'utility',
    price: 150,
  },
  {
    id: 29,
    name: 'Marvin Gardens',
    shortName: 'Marvin',
    type: 'property',
    group: 'yellow',
    price: 280,
    rent: [24, 120, 360, 850, 1025, 1200],
    housePrice: 150,
  },
  {
    id: 30,
    name: 'Go To Jail',
    type: 'goToJail',
    description: 'Go directly to Jail - do not pass Go, do not collect $200',
  },
  {
    id: 31,
    name: 'Pacific Avenue',
    shortName: 'Pacific',
    type: 'property',
    group: 'green',
    price: 300,
    rent: [26, 130, 390, 900, 1100, 1275],
    housePrice: 200,
  },
  {
    id: 32,
    name: 'North Carolina Avenue',
    shortName: 'N.Carolin',
    type: 'property',
    group: 'green',
    price: 300,
    rent: [26, 130, 390, 900, 1100, 1275],
    housePrice: 200,
  },
  {
    id: 33,
    name: 'Community Chest',
    shortName: 'Com.Chest',
    type: 'communityChest',
    description: 'Draw a Community Chest card',
  },
  {
    id: 34,
    name: 'Pennsylvania Avenue',
    shortName: 'Penn. Ave',
    type: 'property',
    group: 'green',
    price: 320,
    rent: [28, 150, 450, 1000, 1200, 1400],
    housePrice: 200,
  },
  {
    id: 35,
    name: 'Short Line Railroad',
    shortName: 'Short Ln.',
    type: 'railroad',
    price: 200,
    rent: [25, 50, 100, 200],
  },
  {
    id: 36,
    name: 'Chance',
    type: 'chance',
    description: 'Draw a Chance card',
  },
  {
    id: 37,
    name: 'Park Place',
    shortName: 'Park Pl.',
    type: 'property',
    group: 'darkBlue',
    price: 350,
    rent: [35, 175, 500, 1100, 1300, 1500],
    housePrice: 200,
  },
  {
    id: 38,
    name: 'Luxury Tax',
    shortName: 'Lux. Tax',
    type: 'tax',
    description: 'Pay $100',
    amount: 100,
  },
  {
    id: 39,
    name: 'Boardwalk',
    type: 'property',
    group: 'darkBlue',
    price: 400,
    rent: [50, 200, 600, 1400, 1600, 1750],
    housePrice: 200,
  },
];

// Property group colors
const GROUP_COLORS = {
  brown: '#8B4513',
  lightBlue: '#87CEEB',
  pink: '#FF69B4',
  orange: '#FF8C00',
  red: '#E63946',
  yellow: '#FFD700',
  green: '#228B22',
  darkBlue: '#1D3557',
  railroad: '#8D99AE',
  utility: '#8D99AE',
};

// Player token colors
const PLAYER_COLORS = [
  '#E63946', // red
  '#1D3557', // blue
  '#F4A261', // gold
  '#228B22', // green
  '#8B4513', // brown
  '#FF69B4', // pink
  '#87CEEB', // light blue
  '#2B2D42', // dark
];

// Default game config
const DEFAULT_CONFIG = {
  startingCash: 1500,
  auctionEnabled: true,
  mortgageEnabled: true,
  freeParkingJackpot: 0,
  jailFine: 'pay50',
  speedDie: false,
  maxPlayers: 6,
};

module.exports = {
  BOARD_SPACES,
  GROUP_COLORS,
  PLAYER_COLORS,
  DEFAULT_CONFIG,
};